name: Build and deploy NGC project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build ngc
      run: |
        docker network create --subnet 172.28.0.0 ngc-sandbox-network
        npm install --location=global @nomocode/ngc
        ngc deploy --env prod
